// Auto-generated by tools/gen_tb_vectors.py -- do not edit by hand.
localparam int TB_INPUT_CH  = 2;
localparam int TB_OUTPUT_CH = 2;
localparam int TB_KERNEL_H  = 3;
localparam int TB_KERNEL_W  = 3;
localparam int TB_TILE_H    = 4;
localparam int TB_TILE_W    = 4;
localparam int TB_STRIDE    = 1;
localparam int TB_IFM_H_EFF = 6;
localparam int TB_IFM_W_EFF = 6;
localparam int TB_IFM_WORDS = 72;
localparam int TB_WGT_WORDS = 36;
localparam int TB_OFM_WORDS = 32;
