`timescale 1ns / 1ps

// Directly instantiates conv_engine (bypassing AXI/CSR), preloads IFM and
// WEIGHT memories from rtl/tb/vectors/{ifm,weight}.mem (generated by
// tools/gen_tb_vectors.py from the golden model), runs one tile, and
// compares the resulting OFM memory against vectors/ofm_expected.mem.
//
// Models conv_engine's IFM and WEIGHT ports as byte-wide synchronous-read
// memories with one cycle of read latency, which is what npu_top presents to
// it (tb_npu_top covers the block RAMs' 32-bit port B), and its OFM port as a
// word-wide memory. Stimulus changes 1 ns after the rising clock edge, clear of
// the edge where conv_engine samples it.
//
// Run with `python tools/run_sims.py`, which compiles it with Vivado's xvlog/xelab/xsim, or with
// the Verilator binary when Vivado is not installed. By hand: xvlog -sv --include rtl/tb
// rtl/conv_engine.sv rtl/tb/tb_conv_engine.sv, xelab tb_conv_engine -s snap, then xsim snap -R
// from a directory holding vectors/.

module tb_conv_engine;

    `include "tb_config.svh"

    localparam int IFM_ADDR_W = 15;
    localparam int WGT_ADDR_W = 17;
    localparam int OFM_ADDR_W = 16;

    logic clk = 0;
    logic rst_n = 0;

    always #5 clk = ~clk;

    // ------------------------------------------------------------
    // DUT config / control
    // ------------------------------------------------------------
    logic        start;
    logic        done;
    logic        busy;

    logic [IFM_ADDR_W-1:0] ifm_addr;
    logic [7:0]            ifm_rdata;

    logic [WGT_ADDR_W-1:0] wgt_addr;
    logic [7:0]            wgt_rdata;

    logic [OFM_ADDR_W-1:0] ofm_addr;
    logic [31:0]           ofm_wdata;
    logic                  ofm_we;

    conv_engine #(
        .IFM_ADDR_W(IFM_ADDR_W),
        .WGT_ADDR_W(WGT_ADDR_W),
        .OFM_ADDR_W(OFM_ADDR_W)
    ) dut (
        .clk        (clk),
        .rst_n      (rst_n),

        .input_ch   (8'(TB_INPUT_CH)),
        .output_ch  (8'(TB_OUTPUT_CH)),
        .kernel_h   (8'(TB_KERNEL_H)),
        .kernel_w   (8'(TB_KERNEL_W)),
        .tile_h     (9'(TB_TILE_H)),
        .tile_w     (9'(TB_TILE_W)),
        .stride     (3'(TB_STRIDE)),

        .start      (start),
        .done       (done),
        .busy       (busy),

        .ifm_addr   (ifm_addr),
        .ifm_rdata  (ifm_rdata),

        .wgt_addr   (wgt_addr),
        .wgt_rdata  (wgt_rdata),

        .ofm_addr   (ofm_addr),
        .ofm_wdata  (ofm_wdata),
        .ofm_we     (ofm_we)
    );

    // ------------------------------------------------------------
    // IFM / WEIGHT memories (read-only, 1-cycle latency)
    // ------------------------------------------------------------
    logic [7:0] ifm_mem [0:TB_IFM_WORDS-1];
    logic [7:0] wgt_mem [0:TB_WGT_WORDS-1];

    initial begin
        $readmemh("vectors/ifm.mem", ifm_mem);
        $readmemh("vectors/weight.mem", wgt_mem);
    end

    always_ff @(posedge clk) begin
        ifm_rdata <= ifm_mem[ifm_addr];
        wgt_rdata <= wgt_mem[wgt_addr];
    end

    // ------------------------------------------------------------
    // OFM memory (write-only)
    // ------------------------------------------------------------
    logic [31:0] ofm_mem [0:TB_OFM_WORDS-1];

    always_ff @(posedge clk) begin
        if (ofm_we) ofm_mem[ofm_addr] <= ofm_wdata;
    end

    // ------------------------------------------------------------
    // Stimulus / checking
    // ------------------------------------------------------------
    logic [31:0] ofm_expected [0:TB_OFM_WORDS-1];
    int errors;

    initial begin
        $readmemh("vectors/ofm_expected.mem", ofm_expected);

        start = 0;
        rst_n = 0;
        repeat (3) @(posedge clk);
        #1 rst_n = 1;
        @(posedge clk);

        #1 start = 1;
        @(posedge clk);
        #1 start = 0;

        wait (done == 1'b1);
        @(posedge clk); // let the last OFM write land

        errors = 0;
        for (int i = 0; i < TB_OFM_WORDS; i++) begin
            if (ofm_mem[i] !== ofm_expected[i]) begin
                $display("MISMATCH at ofm[%0d]: got %08x expected %08x",
                         i, ofm_mem[i], ofm_expected[i]);
                errors++;
            end
        end

        if (errors == 0) begin
            $display("PASS: all %0d OFM words match golden model", TB_OFM_WORDS);
        end else begin
            $display("FAIL: %0d / %0d OFM words mismatched", errors, TB_OFM_WORDS);
        end

        $finish;
    end

    // Safety timeout
    initial begin
        #100000;
        $display("TIMEOUT: done never asserted");
        $finish;
    end

endmodule
