// Auto-generated by tools/gen_tb_vectors.py -- do not edit by hand.
// case 0: Conv1 on test image 0, whole layer
// case 1: non-square tile, stride 2
// case 2: non-square kernel, stride 3
// case 3: 1x1 kernel, 16 input channels
// case 4: 64 input channels, extreme values
localparam int TOP_CASES = 5;
localparam int TOP_INPUT_CH  [TOP_CASES] = '{1, 3, 5, 16, 64};
localparam int TOP_OUTPUT_CH [TOP_CASES] = '{8, 4, 3, 8, 2};
localparam int TOP_KERNEL_H  [TOP_CASES] = '{3, 3, 2, 1, 3};
localparam int TOP_KERNEL_W  [TOP_CASES] = '{3, 3, 4, 1, 3};
localparam int TOP_TILE_H    [TOP_CASES] = '{26, 5, 6, 4, 2};
localparam int TOP_TILE_W    [TOP_CASES] = '{26, 7, 3, 4, 3};
localparam int TOP_STRIDE    [TOP_CASES] = '{1, 2, 3, 1, 1};
localparam int TOP_IFM_BYTES [TOP_CASES] = '{784, 495, 850, 256, 1280};
localparam int TOP_WGT_BYTES [TOP_CASES] = '{72, 108, 120, 128, 1152};
localparam int TOP_OFM_WORDS [TOP_CASES] = '{5408, 140, 54, 128, 12};
