"""Generate $readmemh test vectors for rtl/tb/tb_conv_engine.sv and rtl/tb/tb_npu_top.sv.

For tb_conv_engine: picks a small one-tile conv config, generates a random IFM
window + weight tile, computes the expected OFM tile with the golden model
(golden_model/conv2d.py: conv2d_6for), and writes:

  rtl/tb/vectors/ifm.mem          - input_ch * ifm_h_eff * ifm_w_eff bytes, hex
  rtl/tb/vectors/weight.mem       - output_ch * input_ch * kh * kw bytes, hex
  rtl/tb/vectors/ofm_expected.mem - output_ch * tile_h * tile_w int32 words, hex
  rtl/tb/tb_config.svh            - localparams matching this config

For tb_npu_top: one tile per entry of TOP_CASES, run through the AXI4-Lite CSRs:

  rtl/tb/vectors/top_case<n>_{ifm,weight,ofm}.mem  - as above, per case
  rtl/tb/tb_top_cases.svh                          - the cases' configs as localparam arrays

All .mem files are one hex value per line, suitable for $readmemh.
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "golden_model"))
from conv2d import conv2d_6for  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "rtl", "tb")
VEC_DIR = os.path.join(OUT_DIR, "vectors")

# One-tile config: small enough to simulate quickly, but exercises
# input_ch > 1, output_ch > 1, a 3x3 kernel, and stride 1.
INPUT_CH = 2
OUTPUT_CH = 2
KERNEL_H = 3
KERNEL_W = 3
TILE_H = 4
TILE_W = 4
STRIDE = 1

IFM_H_EFF = (TILE_H - 1) * STRIDE + KERNEL_H
IFM_W_EFF = (TILE_W - 1) * STRIDE + KERNEL_W

# Tiles for the top-level testbench. Each is (name, input_ch, output_ch, kernel_h, kernel_w,
# tile_h, tile_w, stride, data): data "conv1" takes the IFM window from test image 0 and the
# weights from Conv1 in data/; "random" draws both at random; "extreme" fills the IFM with -128 and
# the weights of output channel 0 with -128 and of every other channel with 127, which gives the
# largest positive and negative sums the configuration can produce.
TOP_CASES = [
    ("Conv1 on test image 0, whole layer",    1,  8, 3, 3, 26, 26, 1, "conv1"),
    ("non-square tile, stride 2",             3,  4, 3, 3,  5,  7, 2, "random"),
    ("non-square kernel, stride 3",           5,  3, 2, 4,  6,  3, 3, "random"),
    ("1x1 kernel, 16 input channels",        16,  8, 1, 1,  4,  4, 1, "random"),
    ("64 input channels, extreme values",    64,  2, 3, 3,  2,  3, 1, "extreme"),
]
DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")


def write_mem_i8(path, arr):
    with open(path, "w") as f:
        for v in arr.flatten():
            f.write(f"{int(v) & 0xFF:02x}\n")


def write_mem_i32(path, arr):
    with open(path, "w") as f:
        for v in arr.flatten():
            f.write(f"{int(v) & 0xFFFFFFFF:08x}\n")


def top_case_data(rng, input_ch, output_ch, kernel_h, kernel_w, tile_h, tile_w, stride, data):
    ifm_h = (tile_h - 1) * stride + kernel_h
    ifm_w = (tile_w - 1) * stride + kernel_w
    if data == "conv1":
        ifm = np.load(os.path.join(DATA_DIR, "input.npy"))[0, :, :ifm_h, :ifm_w].astype(np.int8)
        weight = np.load(os.path.join(DATA_DIR, "layer1_0_weight.npy")).astype(np.int8)
    elif data == "extreme":
        ifm = np.full((input_ch, ifm_h, ifm_w), -128, dtype=np.int8)
        weight = np.full((output_ch, input_ch, kernel_h, kernel_w), 127, dtype=np.int8)
        weight[0] = -128
    else:
        ifm = rng.integers(-128, 128, size=(input_ch, ifm_h, ifm_w), dtype=np.int8)
        weight = rng.integers(-128, 128, size=(output_ch, input_ch, kernel_h, kernel_w), dtype=np.int8)
    assert ifm.shape == (input_ch, ifm_h, ifm_w) and weight.shape == (output_ch, input_ch, kernel_h, kernel_w)
    return ifm, weight


def write_top_cases():
    rng = np.random.default_rng(2025)
    fields = {k: [] for k in ("INPUT_CH", "OUTPUT_CH", "KERNEL_H", "KERNEL_W", "TILE_H", "TILE_W",
                              "STRIDE", "IFM_BYTES", "WGT_BYTES", "OFM_WORDS")}
    for n, (name, ic, oc, kh, kw, th, tw, st, data) in enumerate(TOP_CASES):
        ifm, weight = top_case_data(rng, ic, oc, kh, kw, th, tw, st, data)
        ofm = conv2d_6for(ifm, weight, stride=st)
        assert ofm.shape == (oc, th, tw), ofm.shape
        assert np.abs(ofm).max() < 2**31, "OFM exceeds int32"
        write_mem_i8(os.path.join(VEC_DIR, f"top_case{n}_ifm.mem"), ifm)
        write_mem_i8(os.path.join(VEC_DIR, f"top_case{n}_weight.mem"), weight)
        write_mem_i32(os.path.join(VEC_DIR, f"top_case{n}_ofm.mem"), ofm)
        for key, value in zip(fields, (ic, oc, kh, kw, th, tw, st, ifm.size, weight.size, ofm.size)):
            fields[key].append(value)
        print(f"top case {n}: {name}: {ofm.size} OFM words, |OFM| up to {int(np.abs(ofm).max())}")

    svh_path = os.path.join(OUT_DIR, "tb_top_cases.svh")
    with open(svh_path, "w") as f:
        f.write("// Auto-generated by tools/gen_tb_vectors.py -- do not edit by hand.\n")
        for n, case in enumerate(TOP_CASES):
            f.write(f"// case {n}: {case[0]}\n")
        f.write(f"localparam int TOP_CASES = {len(TOP_CASES)};\n")
        for key, values in fields.items():
            f.write(f"localparam int TOP_{key:<9s} [TOP_CASES] = '{{{', '.join(str(v) for v in values)}}};\n")
    print(f"wrote {svh_path}")


def main():
    os.makedirs(VEC_DIR, exist_ok=True)

    rng = np.random.default_rng(42)
    ifm = rng.integers(-128, 128, size=(INPUT_CH, IFM_H_EFF, IFM_W_EFF), dtype=np.int8)
    weight = rng.integers(-128, 128, size=(OUTPUT_CH, INPUT_CH, KERNEL_H, KERNEL_W), dtype=np.int8)

    ofm = conv2d_6for(ifm, weight, stride=STRIDE)
    assert ofm.shape == (OUTPUT_CH, TILE_H, TILE_W), ofm.shape

    write_mem_i8(os.path.join(VEC_DIR, "ifm.mem"), ifm)
    write_mem_i8(os.path.join(VEC_DIR, "weight.mem"), weight)
    write_mem_i32(os.path.join(VEC_DIR, "ofm_expected.mem"), ofm)

    svh_path = os.path.join(OUT_DIR, "tb_config.svh")
    with open(svh_path, "w") as f:
        f.write("// Auto-generated by tools/gen_tb_vectors.py -- do not edit by hand.\n")
        f.write(f"localparam int TB_INPUT_CH  = {INPUT_CH};\n")
        f.write(f"localparam int TB_OUTPUT_CH = {OUTPUT_CH};\n")
        f.write(f"localparam int TB_KERNEL_H  = {KERNEL_H};\n")
        f.write(f"localparam int TB_KERNEL_W  = {KERNEL_W};\n")
        f.write(f"localparam int TB_TILE_H    = {TILE_H};\n")
        f.write(f"localparam int TB_TILE_W    = {TILE_W};\n")
        f.write(f"localparam int TB_STRIDE    = {STRIDE};\n")
        f.write(f"localparam int TB_IFM_H_EFF = {IFM_H_EFF};\n")
        f.write(f"localparam int TB_IFM_W_EFF = {IFM_W_EFF};\n")
        f.write(f"localparam int TB_IFM_WORDS = {INPUT_CH * IFM_H_EFF * IFM_W_EFF};\n")
        f.write(f"localparam int TB_WGT_WORDS = {OUTPUT_CH * INPUT_CH * KERNEL_H * KERNEL_W};\n")
        f.write(f"localparam int TB_OFM_WORDS = {OUTPUT_CH * TILE_H * TILE_W};\n")

    print(f"wrote {VEC_DIR}/ifm.mem ({ifm.size} bytes)")
    print(f"wrote {VEC_DIR}/weight.mem ({weight.size} bytes)")
    print(f"wrote {VEC_DIR}/ofm_expected.mem ({ofm.size} words)")
    print(f"wrote {svh_path}")
    print("\nexpected OFM tile:")
    print(ofm)

    print()
    write_top_cases()


if __name__ == "__main__":
    main()
